### ISSUE TITLE
Default credentials - fresh install

### ISSUE THREAD

**Issue by gridworkz** [fairnesscoop/permacoop#129]
Hello - what are the default credentials to login on a fresh install? Cheers, Dave

Update - figured it out:

curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"email":"john@doe.com","password":"john"}' \
  http://127.0.0.1:3000/api/login

btw: my client is running on port 3000.

It didn't seem to create the user (john@doe.com) for me during the install - just a docker user:

permacoop=# select * from user;
  user  
--------
 docker
(1 row)

permacoop=# select * from user_administrative;
 id | joiningDate | leavingDate | annualEarnings | transportFee | healthInsurance | executivePosition | contract 
----+-------------+-------------+----------------+--------------+-----------------+-------------------+----------
(0 rows)

permacoop=# select * from customer;
 id | name | createdAt | addressId 
----+------+-----------+-----------
(0 rows)

**Comment by mmarchois** [comment]
Did you use the command `make install`? It launches the project setup as well as the database migration.
Otherwise you can also use the command `make database-migrate`.

**Comment by gridworkz** [comment]
Thanks, I'll check that out.
