### ISSUE TITLE
As a Developer I'd like to lint and prettify my code

### ISSUE THREAD

**Issue by Volubyl** [fairnesscoop/permacoop#137]
Using eslint and prettier to lint and prettify the front-end code base could save a lot of time and avoid many headaches.

Svelte has a eslint configuration available https://github.com/sveltejs/eslint-plugin-svelte3. This configuration in combinaison with eslint recommended and `airbnb base` ( the full airbnb eslint conf embed rules for react) could be a perfect match.

Here is a configuration example : https://github.com/babichjacob/sapper-typescript-graphql-template/blob/main/.eslintrc.json

**Comment by mmarchois** [comment]
Go go go ! :)
