### ISSUE TITLE
ETQ que dev je souhaiterais déployer automatiquement mon application lors de chaque merge sur master

### ISSUE THREAD

**Issue by Volubyl** [fairnesscoop/permacoop#156]
Actuellement (depuis #276), le déploiement de Permacoop se fait manuellement dans le terminal, en lançant `make deploy env=prod`.

**Proposition**

Modifier la conf GitHub Actions pour lancer le déploiement automatiquement lors d'un merge sur `master`.

**Motivation**

Avantages :
* Réduire la friction à la contribution : tout-e contributeur-ice pourra déployer en ayant sa PR mergée, sans avoir à [faire le setup de déploiement décrit dans la documentation](https://github.com/fairnesscoop/permacoop/tree/master/prod#how-to-deploy).

Risques :
* Le vault-password doit être stocké aussi en dehors de GitHub Actions. Il faut garder la possibilité de déployer ou intervenir manuellement.

**Implémentation**

* Générer des clés SSH pour GitHub Actions
* Les ajouter à `~/.ssh/known_hosts` sur le serveur de prod
* Les ajouter en secrets dans GitHub Actions
* Configurer une _deploy step_ qui les ajoute dans `/.ssh/id_rsa(.pub)`, que Ansible utilisera lorsqu'on lancera `cd ansible && make deploy env=prod`.

**Comment by Volubyl** [comment]
@mmarchois @ip512 @NicolasDievart 

Cette tâche est vraiment sujette à discussion. Je propose cette idée car ce worlflow me parraît  bien mais p-e qu'il est overkill ou non prio pour le moment.

Qu'en pensez-vous ?

**Comment by ip512** [comment]
À mon avis, il faudrait dans un premier temps le mettre en place sur un environnement de test/staging.
On pourrait utiliser cet environnement comme démo, mais dans ce cas il faudrait prévoir un minimum de fixtures pour pouvoir jouer avec.

**Comment by florimondmanca** [comment]
On a désormais la doc du processus de déploiement manuel actuel ici : https://github.com/fairnesscoop/permacoop/tree/master/prod

Dans la continuité de la discussion, j'envisagerais ça :

1. Configurer un environnement de test/staging, genre https://staging.permacoop.fairness.coop. On y activera le déploiement auto en cours de développement, en gardant le process manuel en prod pour l'instant. Quand le déploiement auto semblera robuste, on pourra le faire sur la prod aussi.
2. Ajouter `.github/workflows/staging.yml` avec un job `deploy` qui se lancerait à chaque push sur `master` (ou autre branche avec laquelle on voudrait jouer pour déclencher des déploiements de test).
    - Pour l'instant, ce job referait _grosso modo_ le process manuel actuel en lançant un script via SSH : `git pull`, `npm run build` client et serveur, relance de `pm2`. Il faudra générer une clé SSH spécifique et la mettre dans les `$secrets` sur GitHub.
    - Une fois que ce sera opérationnel, on pourra ensuite voir pour "améliorer" / "sophistiquer" le process (par ex avec Docker… Même si ça pose la question de leur taille, de leur stockage, du registry à utiliser, etc : est-ce qu'on en aura vraiment besoin ? À voir… D'où cette étape incrémentale.)

**Comment by florimondmanca** [comment]
On a un avis sur l'outil de déploiement de PM2 ? https://pm2.keymetrics.io/docs/usage/deployment/. Apparemment ça ne prend tjr pas en compte le reload éventuel des applications.

Je me dis aussi qu'on peut commencer par bidouiller des scripts SSH, mais qu'assez vite il faudra aller sur des outils + robustes, sans être overkill non plus. Mais dans le domaine du "DevOps côté infrastructure" je suis preneur de bonnes pratiques… À discuter.

**Comment by florimondmanca** [comment]
Il y a du changement avec l'adoption d'Ansible #276.

Je vais màj la description de l'issue avec ce qui me semble nécessaire désormais
