### ISSUE TITLE
ETQ Salarié je peux noter un pourcentage de réduction sur chacune des lignes du devis.

### ISSUE THREAD

**Issue by hmmarchois** [fairnesscoop/permacoop#168]
Quand je prépare un devis, je peux ajouter un taux de réduction en plus des quantités et du taux HT. Le taux de réduction doit être en pourcentage et être pris en compte dans le montant du devis final. 
CF Devis sur zoho par exemple.

**Comment by florimondmanca** [comment]
On a retiré les devis de Permacoop, ce ticket est obsolète
