### ISSUE TITLE
ETQ Salarié je vois apparaître les jours fériés sur mon faircalendar

### ISSUE THREAD

**Issue by hmmarchois** [fairnesscoop/permacoop#169]
Aujourd'hui les jours fériés n'apparaissent pas et quand on veut noter quelque chose sur un jour férié il est indiqué comme "non valide".

Ils doivent apparaître en grisé quand on est sur une vue du mois (comme les jours des mois précédents ou suivants) et être notés fériés.
Et quand on veut noter quelque chose sur un jour férié, il doit être indiqué : "vous ne pouvez pas saisir d'informations sur un jour férié."

**Comment by florimondmanca** [comment]
À noter, je ne sais pas comment on gère la liste des jours fériés ajd, mais ils sont publiés ici en open data : https://www.data.gouv.fr/fr/datasets/jours-feries-en-france/

Il y a sur cette page un flux ICS et un fichier CSV.

On pourrait peut-être faire en sorte que FairCalendar affiche ce flux ICS. Ça rendrait visible les jours fériés et éviterait d'être tenté d'y ajouter des choses.
