### ISSUE TITLE
ETQDev je souhaite avoir une commande pour analyser le poids du bundle généré.

### ISSUE THREAD

**Issue by mmarchois** [fairnesscoop/permacoop#174]
Utiliser source-map-explorer pour pouvoir identifier les optimisations à réaliser.

**Comment by florimondmanca** [comment]
Ce ticket sera partiellement résolu par #415 : le bundle est considérablement réduit et `esbuild` affiche le poids des différents fichiers par défaut

```bash
> make assets

  dist/public/faircalendar.js   87.0kb
  dist/public/main.css          11.3kb
  dist/public/faircalendar.css   7.0kb
  dist/public/main.js            2.9kb

⚡ Done in 54ms
```
