### ISSUE TITLE
ETQ Comptable je peux accéder au tableau récap Paie du mois.

### ISSUE THREAD

**Issue by hmmarchois** [fairnesscoop/permacoop#187]
Tableau récapitulatif avec, pour chaque salarié: 
- NOM
- Prénom
- Matricule
- Type de contrat
- Date d'entrée dans la coopérative
- Salaire Brut annuel 
- Salaire Brut Mensuel
- Temps Partiel ou Temps Complet
- Montant de l'abonnement mensuel de transport
- Nombre de tickets resto à donner
- Abonnement à la Mutuelle (Oui/Non)
- Nombre de jours de Congés Payés
- Date de début/ Date de fin --> Possibilité d'avoir plusieurs périodes distinctes de congés sur le mois
- Nombre de congés exceptionnels (avec les dates)
- Nombre de jours arrêt maladie (avec les dates)
- Nombre de jours de congés sans solde
- Case commentaires pour toute communication nécessaire entre les RH et la Paie

**Comment by florimondmanca** [comment]
Ce qu'il manque ajd en termes de données :

* Matricule : on n'a pas encore cette info (à voir comment elle est définie ? puis à mettre dans `user_administrative`)
* Temps partiel / temps complet : on ne stocke pas encore cette info (à mettre dans `user_administrative`)

J'ai regardé pour une 1ère itération qui génère un PDF à partir des données en base en cliquant sur un unique bouton. Techniquement ça passe. Mais il faudrait réfléchir à comment permettre d'ajouter un commentaire avec une bonne UX.

Il y a aussi la question de si un PDF est le + approprié, car celui-ci n'est pas éditable : on perd la possibilité de "négocier avec la BDD" ! Donc en cas d'erreur (code, données…), on devra corriger le bug, or pour la paie ça peut être critique… Peut-être étudier la voie d'un **document**, genre `.odt` ou `.docx`. Excel est à éviter en raison des données multi-niveaux (liste de congés de taille variable au sein de chaque item).

**Comment by florimondmanca** [comment]
Autre point technique, le calcul des tickets resto "consommés" sur le mois se fait pour l'instant de manière programmatique dans le code serveur, pour un utilisateur donné. Il faudrait ajouter un moyen efficace d'obtenir cette valeur pour tous les utilisateurs d'un coup (nécessaire pour la génération des éléments de paie, puisqu'on affiche tous les salariés). On pourrait peut-être le faire en BDD avec une [vue](https://www.postgresqltutorial.com/managing-postgresql-views/) dont on ne prendrait qu'un élément pour la requête "pour un utilisateur donné". À voir.

**Comment by florimondmanca** [comment]
On a le tableau des éléments de paie depuis un certain temps, je crois que ce ticket est obsolète
