### ISSUE TITLE
What do you mean by reserved for worker-owned business?

### ISSUE THREAD

**Issue by novidtech** [fairnesscoop/permacoop#190]
Hi, can anyone use this project? What do you mean by reserved for worker-owned business?

**Comment by mmarchois** [comment]
Hi, it’s aimed for cooperatives mainly but anyone can use it. All data is accessible (readable) to all connected persons in full transparency.

**Comment by novidtech** [comment]
Ah ok. Thanks. That makes sense. Thank you. Amazing work by the way

Kind regards,

Rohan Groombridge
Novidtech | Director
E: Rohan.Groombridge@Novidtech.com.au
M: 0409860838
