### ISSUE TITLE
[Bug] Lorsque je crée un congés d'une demi journée, je me retrouve avec 0 ou -0.5

### ISSUE THREAD

**Issue by NicolasDievart** [fairnesscoop/permacoop#195]
Lorsque je crée un congés sur une journée et que je remplie "toute la journée" à "non" : 

![Screenshot_2021-03-26 Faire une demande de congé - Permacoop](https://user-images.githubusercontent.com/4649817/112651961-32bff900-8e4d-11eb-92e4-85f6a4732f8c.png)

J'obtiens le résultat suivant : 

<img width="1142" alt="Screenshot 2021-03-26 at 15 58 46" src="https://user-images.githubusercontent.com/4649817/112652218-73b80d80-8e4d-11eb-8f5e-b99a28191222.png">

Au lieu de la mention "0.5 jour", j'ai "-0.5 jour"

**Comment by florimondmanca** [comment]
Ce ticket est obsolète, l'affichage est bon depuis longtemps
