### ISSUE TITLE
Suivi de la participation / épargne salariale

### ISSUE THREAD

**Issue by mmarchois** [fairnesscoop/permacoop#250]
L'objectif est d'avoir un suivi des "comptes bloqués" des coopérateurs/salariés dans le cadre de l'accord de participation.

### Vues

Vue tableau : pour chaque utilisateur :

* Nom, prénom
* Solde (somme des crédits et des débits)
* Voir les détails

Vue détail : pour chaque _opération_ sur le compte bloqué :

* Date
* Personne qui a effectué l'opération
* Montant (positif si crédit, négatif si débit)

### Contexte additionnel

Hélène a mentionné le fait que coop tech avait un outil similaire, dont on pourrait potentiellement s'inspirer. L'objectif de permacoop est d'avoir un outil qui centralise tout ce dont on a besoin au bon fonctionnement de la coopérative et d'en faire une vitrine tech/produit.

**Comment by florimondmanca** [comment]
Dans #415 je débranche cette feature du front

Je me demande s'il ne vaudrait pas mieux qu'on la retire du back aussi

Motivation : on fait le suivi sur un Excel pour l'instant et je me dis que c'est tout à fait suffisant, non ? On essaie de réduire drastiquement le périmètre fonctionnel de Permacoop pour faciliter sa maintenance.

**Comment by florimondmanca** [comment]
Pour l'instant on fait le suivi Excel et ça a l'air de suffire. C'est aussi plus flexible.

Pour clore ce ticket je dirais qu'il faudrait retirer le code back sur les `UserSavings`
