### ISSUE TITLE
Ne garder le Docker Compose local que pour la base de données

### ISSUE THREAD

**Issue by florimondmanca** [fairnesscoop/permacoop#274]
_Thoughts?_

Plus sérieusement, voici mon raisonnement...

## Analyse

Actuellement on utilise un Docker Compose _uniquement pour le développement local_.

Notre expérience sur Catalogage a montré que, pour des utilisateurs techniques capables d'installer des prérequis (Node, en gros), ça n'est pas nécessaire.

Ça induit peut-être plus de problèmes que ça n'en résout, par exemple les problèmes de permissions, le mapping de volumes pour faire fonctionner le hot reload, voire désormais l'installation de Docker lui-même (Docker Desktop sur Linux ?).

De plus, ça ajoute de la configuration qui n'est pas non plus utilisée pour la prod, donc pas d'avantage de ce côté-là par rapport à un setup "sur l'hôte" classique.

@mmarchois a mentionné avoir retiré Docker pour le dev chez RF. J'aimerais entendre son avis sur l'idée de le retirer de Permacoop aussi.

## Proposition

* Retirer de docker-compose.yml les services suivants :

  * api
  * client
  * nginx

* Garder `database` car l'installation de PostgreSQL est plus fastidieuse que lancer un `npm ci` pour le client et l'API.

* Réorganiser le `Makefile` pour que le install, build, start, test, etc se fassent en communiquant avec le client ou l'API via le dossier local.

Par exemple, pour `start` :

```make
prefix = ./tools/colorize_prefix.sh

start: ## Serve API, client, Tailwind and DB in parallel
	make -j 4 start-api start-client start-tailwind start-db

start-api: ## Run API
	${prefix} [api] 30 "cd server && npm run start:dev"

start-client: ## Run client
	PORT=3001 ${prefix} [client] 31 "cd client && npm run dev"

start-tailwind:
	${prefix} [tailwind] 36 "cd client && npm run watch:tailwind"

start-db:
	${prefix} [db] 34 "${compose} up -d -- database"
```

`make -j` est ici utilisé comme un job launcher léger pour lancer tous les serveurs en parallèle.

[`colorize_prefix.sh`](https://github.com/etalab/catalogage-donnees/blob/master/tools/colorize_prefix.sh) est un script à placer dans le repo pour ajouter par exemple ici un [client] colorisé en rouge, permettant de distinguer les logs des divers jobs lancés par `make -j`.

**Comment by mmarchois** [comment]
Je suis complètement d'accord avec ton analyse, je n'ai rien à rajouter d'autre. Le garder pour la DB est effectivement utile, si demain on doit installer des systèmes de cache ou des workers, idem.
En l'état on peut donc sortir du setup toute la partie Node, cela va alléger l'installation (biensur en spécifiant dans le package.json la version minimale requise de Node)
