### ISSUE TITLE
ETQ salarié-e je peux voir la liste des primes de participations

### ISSUE THREAD

**Issue by AntoineSmagghe** [fairnesscoop/permacoop#295]
## User story

ETQ salarié-e je peux voir la liste des primes de participations 

## Fonctionnement actuel

Dans la partie RH -> épargne salariale, lorsque l'on ajoute une prime de participation, rien ne s'affiche.

## Fonctionnement souhaité

Dans la partie épargne salariale, afficher la liste des primes de participations renseignées.

**Comment by florimondmanca** [comment]
Salut @AntoineSmagghe, je crois que c'est un duplicata de #250, non ? Il vaut peut-être mieux continuer la discussion sur cette fonctionnalité là-bas.

Par ailleurs, un petit retour d'expérience méthodologie si je peux me permettre. La structure "fonctionnement actuel / fonctionnement souhaité" fonctionne bien pour décrire un bug. Pour une nouvelle fonctionnalité, avec @Volubyl ce qu'on a trouvé pas mal sur la mission Catalogage avec Etalab c'était une structure comme suit :

* User story (ou user stories pour une epic qui rassemble plusieurs US)
* Critères d'acceptation :
  * Une checklist d'affirmations qui doivent être satisfaites avant de pouvoir fermer le ticket.
  * Exemple :
    * [ ] Depuis la page bidule, je peux accéder à la gestion des machins.
    * [ ] Sur la page de gestion des machins, je peux récupérer un résumé de mes machins.
    * [ ] Je peux ne récupérer les machins que pour un mois donné.
    * [ ] La page est accessible aux utilisateurs connectés seulement.
  * Ces critères doivent être définis en des termes fonctionnels, c'est-à-dire suffisamment "haut niveau" pour laisser la voie ouverte à différents choix d'implémentation.
    * Par exemple "accéder à la page trucmuche" pourrait être fait à l'aide d'un lien, d'un bouton, tout ça étant des choix de design/implémentation. Mais tant qu'on peut accéder à trucmuche, on considère que ça remplit le critère.
* Design : 
  * Des indications d'UI/UX, par exemple une maquette, un wireframe, ou plus basiquement une description textuelle de l'allure graphique du résultat attendu.
  * Exemple : "Lien cliquable sur la page bidule avec le label 'Accéder aux machins'"
* Implémentation : 
  * Une TODO list plus technique. Chaque item peut faire l'objet d'une PR, auquel cas on le remplacera par l'item en question. Le format checklist permet de suivre l'avancement de l'implémentation, au cas où l'user story est trop complexe pour être faite d'une traite.
  * Exemple : 
    * [ ] Créer l'endpoint `GET /api/machins`
    * [ ] Créer la page "Gestion des machins"
    * [ ] Ajouter un lien `<a>` sur la page bidule

Su #250 la structure du ticket est encore trop ad-hoc, ça pourrait être pas mal de voir comment on le re-rédigerait en adoptant cette structure ?

**Comment by AntoineSmagghe** [comment]
Effectivement on peut fermer cette issue en faveur de #250
