### ISSUE TITLE
ETQ coopérateur/salarié, je peux avoir un aperçu des demandes de congé sur mon tableau de bord

### ISSUE THREAD

**Issue by Volubyl** [fairnesscoop/permacoop#332]
# Description du besoin

Lorsque que je me connecte sur permacoop, je souhaiterais avoir un aperçu des demandes de congés des *autres* coopérateurs salariés qui *n'ont pas encore été validées*

# Règles métier

- qqn ayant fait sa demande de congé ne peut pas valider sa propre demande

## A anticiper pour le futur :

- (nice to have) les demandes de congés des cogérants soit uniquement affichés sur la tableau de bord d'un coopérateur référent (pour l'année 2023-2024 c'est Mathieu)
- (nice to have) les cogérants ne voient pas les demandes de congés des autres cogérants

Note : les "nice to have" peuvent faire l'objet d'une issue dédié. Cependant, ETQ PO, j'aurai besoin de comprendre ce que cela implique au niveau difficulté d'implem

# Considérations UX/UI

- le tableau de bord est la page sur laquelle on arrive directement après s'être connecté.
- les demandes de congés doivent être présentées sous forme de tableau de donnée
- les informations à afficher sont :  la date du début et de fin du congé, le nom et le prénom de la personne ayant effectué la demande de congé ainsi que le commentaire ajouté lors de demande de congé (si il existe)
- dans une colonne du tableau, j'ai un "bouton d'action". Cliquer dessus, redirige vers la page de gestion des congés.

# Scénarios

## Scénario "tout va bien"

- ETQ coopérateur/salarié, je me connecte sur permaccop.
- Sur mon tableau de bord, j'ai la liste des demandes de congés en cours.
- En cliquant sur le bouton d'action, je peux valider une demande de congé
- une fois que la demande de congé a été validée, je ne la vois plus dans le tableau ni sur la page de gestion des congés

## Scénario "la validation de congé n'a pas fonctionné"

Si ce scénario se produit, il faut que l'utilisateur soit au courant que quelque chose s'est mal passé. 
La méthode pour prévenir l'utilisateur peut être librement choisie par la personne développant la fonctionnalité

# Critères d'acceptation

- [ ] en me connectant, je vois la liste des demandes de congés des autres coopérateurs/salariés
- [ ] dans ce tableau, je peux voir le nom, prénom de la personne ayant effectué la demande de congé ainsi que la date de début et de fin de cette demande de congé
- [ ] en cliquant sur le bouton d'action, je suis redirigé vers la page de gestion des congés
- [ ] une fois que la demande de congé a été validée, je ne la vois plus dans le tableau ni sur la page de gestion des congés

**Comment by benpaquier** [comment]
@Volubyl je suis pas sûr à 100% de la pertinence d'avoir le commentaire dans l'aperçu des demandes de congés. Pour l'instant je les ai mis dans la PR, à discuter si tu le souhaites!

**Comment by benpaquier** [comment]
Après discussion sur https://github.com/fairnesscoop/permacoop/pull/359, voici le découpage:

1. Limitation du nb de demandes de congés renvoyés par l'endpoint: https://github.com/fairnesscoop/permacoop/pull/370
2. UX simplifiée avec le nombre de demandes de congé en attente et un lien vers la page de demandes de congé :https://github.com/fairnesscoop/permacoop/pull/371
