### ISSUE TITLE
Suppression de congés acceptés

### ISSUE THREAD

**Issue by benpaquier** [fairnesscoop/permacoop#358]
As a user, I am able to delete an accepted leave request.

- I should be able to delete an accepted leave request if it is set in the future.
- I should not be able to delete an accepted leave request if it is set in the past.

**Comment by florimondmanca** [comment]
Cette issue avait été traitée par #357 je pense, en tout cas à ce jour on peut effectivement supprimer les congés acceptés tant qu'ils sont à venir
