### ISSUE TITLE
Ajout du forfait mobilité durable 

### ISSUE THREAD

**Issue by benpaquier** [fairnesscoop/permacoop#362]
### ETQ coopérateur/salarié, j'indique le montant de mon forfait mobilité durable afin qu'il soit pris en compte lors de la paie

De la même façon que pour le transport:

- [ ] Ajout du champs "mobilité durable" dans le formulaire d'ajout d'un coopérateur/employé
- [ ] Ajout du champs "mobilité durable" dans le formulaire de mise à jour d'un coopérateur/employé
- [ ] Ajout de la colonne "mobilité durable" dans le tableau "éléments de paie"
- [ ] Ajout de la colonne "mobilité durable" dans l'export csv "éléments de paie"

**Comment by florimondmanca** [comment]
:+1:

Proposition de reformulation de la user story avec un "afin que" (ça permet d'ancrer le besoin utilisateur) :

> ETQ coopérateur/salarié, j'indique le montant de mon forfait mobilité durable afin qu'il soit pris en compte lors de la paie
