### ISSUE TITLE
Afficher les l'état des congés sur l'année en cours pour chaque coopérateurs

### ISSUE THREAD

**Issue by benpaquier** [fairnesscoop/permacoop#364]
### En tant que coopérateur, je souhaiterais avoir un aperçu de l'état de mes congés et des congés des autres coopérateurs au cours de l'exercice actuel.

Dans le cadre du forum ouvert du 17/03/2023, la réflexion à été initiée concernant le format des congés au sein de Fairness. La direction semble aller vers la fin des "congés illimités" pour augmenter le nombre de congés payés dits "classiques". 

### Idée
Créer un tableau avec chaque coopérateur, avec en colonnes: Prénom Nom | Nombre de jour pris | Nombre de jours restant.
L'endroit où l'on affiche ce tableau dans permacoop reste à définir: page dédiée, sur le dashboard, sur la page "congés",...

### Pistes pour aller plus loin
- Un coopérateur ne peut plus faire de demande de congé payés une fois qu'elle/il a atteint le nombre maximal de jours.
- Un coopérateur peut voir son historique de jours de congés. Dans l'idée, pouvoir filtrer la vue existante pour récupérer les congés d'un seul coopérateur
- ...

**Comment by florimondmanca** [comment]
Ce ticket n'est-il pas un _duplicate_ par rapport à #332 ?

**Comment by florimondmanca** [comment]
## UI/UX

On pourrait imaginer que la page "Congés" ait deux vues :

* Vue "Liste" : correspondant à l'actuel tableau
* Vue "Résumé" : montrerait les informations proposées ici

## Calcul

Je pense qu'il faut aussi creuser creuser la question du calcul.

### Analyse

Le calcul est dans la pratique déjà fait par le cabinet comptable, qui fait figurer dans les fiches de paie deux notions :

* Acquis
* Pris
* Solde

Le tout est dupliqué dans deux colonnes : "Congés N-1" et "Congés N"

D'après ma compréhension, le "N" fait référence ici à la **période de référence**, qui est **du 1er juin au 31 mai**.

Je suis arrivé en novembre 2021. J'ai comparé ma fiche de paie de mai 2022, juin 2022 et juillet 2022.

Je vois que jusqu'à mai 2022, ma colonne "Congés N-1" était vide. Logique, je n'étais pas là sur la période de référence précédente (1er juin 2020 - 31 mai 2021).

En juin 2022, la colonne "Congés N-1" se remplit avec ces valeurs :

* Acquis = 15 :
  * Ça correspond à la période entre le 02/11/2021 (date d'arrivée) et le 31 mai 2022 (fin de la période de référence considérée).
  * On trouve les infos sur le règle de calcul ici : (A) [Congés payés (service-public.fr)](https://www.service-public.fr/particuliers/vosdroits/F2258) et là : (B) [L'absence du salarié](L'absence du salarié est-elle prise en compte pour le calcul de ses congés ?)
  * La règle de calcul est la suivante : "Que vous travaillez à temps plein ou à temps partiel, vous bénéficiez de 2.5 jours ouvrables par mois de travail effectif" (cf (A)).
  * Nous on ne travaille pas le samedi, donc on ne calcule pas en _jours ouvrables_ (du lundi au samedi), mais en _jours ouvrés_ (du lundi au vendredi).
  * Il n'y a donc pas 2.5 jours de congés payés acquis par mois, mais environ 2.08 (plus précisément 25/12 = 25 jours ouvrés / 12 mois).
  * De plus, "Lorsque le nombre de jours de congés acquis n'est pas un nombre entier, la durée du congé est portée au nombre entier immédiatement supérieur" (cf (A)).
  * J'ai été présent 7 mois effectifs (de novembre à mai, sachant que "Toute période équivalente à 4 semaines ou 24 jours est assimilée à un mois de travail effectif"), et 7 x 25/12 = 14.5833... ce qui est arrondi à 15. CQFD :smiley: 
* Pris = 13.50 : c'est la somme des congés pris entre le 1er juin 2021 et le 31 mai 2022.

  Si j'exécute la requête SQL suivante sur la prod (en mode lecture seule !) :

  ```sql
  -- `leave.time` est un nombre de minutes
  -- En l'espèce, 420 pour 1 jour et 210 pour 0.5 jour
  -- => Diviser par 60 le ramène en heures
  --    Puis on divise par 7 qui est le temps de travail quotidien
  --    pour obtenir un nombre de jours en base 35h/semaine
  SELECT SUM(leave.time::float) / 60 / 7
  FROM leave
  JOIN leave_request ON leave."leaveRequestId" = leave_request.id
  WHERE leave_request."userId" = '<monUserID>'
  AND leave.date >= '2021-06-01'
  AND leave.date < '2022-06-01';
  ```

  J'obtiens `18` jours. Je ne suis pas sûr de savoir d'où provient la différence avec les 13.5. "Congés illimités" à l'insu de mon plein gré ?

* Solde = 1.50 : on s'aperçoit ici qu'on pratiquait déjà le report des jours de congés à la période de référence suivante (au lieu qu'ils ne soit annulés). Ça doit être un "héritage" du passé de Fairness (remontant peut-être jusqu'à ELAO ?) que les cabinets comptables successifs ont gardé.

Toujours en juin 2022, la colonne "Congés N" devient :

* Acquis = 2.08 :
  * Cela correspond à 25 jours de congés payés annuels / 12 mois = 2.0833...
  * :warning: En juillet 2022, la valeur passe à 4.17, ce qui n'est pas 2 * 2.08 (= 4.16), mais bien 2 * 25/12 = 4.1666....
    * => **La ligne "Acquis" est donc le `ceil()` à 2 décimales de `n` * 25/12**, où `n` est le nombre de mois écoulés depuis le début de la période de référence. En juin n = 1, en juillet n = 2, etc.
  * La valeur 25 est le **nombre de congés payés annuels**, qui jusqu'ici était bien de 5 semaines de 5 jours ouvrables.
* Pris = (vide) (= 0)
* Solde = 2.08

### Quoi afficher ?

Pour afficher "l'état des congés, il faudrait donc à mon avis afficher l'équivalent de ces deux colonnes "Congés N-1" et "Congés N".

* Acquis N-1
* Pris N-1
* Solde N-1
* Acquis N
* Pris N
* Solde N

La colonne "Congés N-1" est importante surtout pour le **Solde N-1**

* Cest la **réserve de congés** reportée d'année en année.
* Lorsqu'un congés en période N sera pris, il ira d'abord piocher dans cette réserve.
* Par exemple :
  * Il me restait 1.5 jour en juin 2022.
  * J'ai pris une semaine de congés (5 jours) en juillet 2022
  * Le Pris N-1 est passé ce mois-là de 13.5 à 15, amenant le Solde N-1 à 0. Le Pris N est alors passé de 0 à 3.5(au lieu de 5 si le Solde N-1 n'avait pas été pris en compte).

### Paramètres de calcul

* Période de référence : on peut la fixer à "1er juin -> 31 mai", ce qui est le standard (bien que théoriquement elle puisse être fixée différemment).
* Nombre de jours de congés payés : actuellement 25 (5 semaines), demain peut-être 31 (6 semaines)
* Temps de travail quotidien : actuellement 7h par jour (420 minutes)

**Comment by Volubyl** [comment]
:warning: Syntec prévoit aussi des jours de congés en plus en fonction de l'ancienneté

Source https://www.syntec.fr/convention-collective/conges/

**Comment by florimondmanca** [comment]
Je ferme préventivement puisqu'on a #381 désormais
