### ISSUE TITLE
[EPIC] ETQ salarié.e, je souhaite pouvoir voir la nombre de jours de congé payé qu'il me reste pour cette année.

### ISSUE THREAD

**Issue by Volubyl** [fairnesscoop/permacoop#381]
## Contexte

En juin 2023, un accord d'entreprise modifiant le nombre de congés payé a été signé. Celui-ci permet aux salarié.e.s de Fairness de bénéficier de 7 semaines de congé payés au lieu des 5 prévues par la loi.

##### Jours ouvrés/ Jours ouvrables

Les jours ouvrables sont tous les jours de la semaine, sauf :

- le jour consacré au repos hebdomadaire (c’est-à-dire, en général, le dimanche) ;
 - les jours fériés et chômés dans l’entreprise.

Les jours ouvrés sont tous les jours habituellement travaillés dans l’entreprise (par exemple : du lundi au vendredi). 

En général, les congés payés sont décomptés en jours ouvrables mais rien n’interdit à un employeur de les calculer dans les jours ouvrés. 

Cette méthode ne doit cependant pas défavoriser le/la salarié·e.

**Chez Fairness, nous décomptons les jours de congés en jours ouvrés.**

#### Jours de travail effectif

Par travail effectif, la législation entend uniquement des périodes pendant lesquelles le/la salarié·e a été à son poste de travail.

Sont assimilés à du travail effectif, notamment :

- les périodes de congés payés de l’année précédente ;
- les périodes de congé de maternité, de paternité et d’accueil de l’enfant et d’adoption ;
- les contreparties obligatoires, sous forme de repos, des heures supplémentaires accomplies dans la limite du contingent annuel ;
- les jours de repos accordés au titre d’un accord collectif, comme pour la « réduction du temps de travail » ;
- les périodes, dans la limite d’une durée ininterrompue d’un an, pendant lesquelles l’exécution du contrat de travail est suspendue pour cause d’accident du travail ou de maladie professionnelle ;
- les périodes pendant lesquelles un·e salarié·e se trouve maintenu·e ou rappelé·e sous les drapeaux à un titre quelconque ;
- certains congés de formation.

##### Exceptions

 Les absences pour maladie (ou pour grève) ne sont pas considérées comme du travail effectif, sauf en cas de dispositions conventionnelles plus favorables. Un·e salarié·e qui a été en arrêt de travail pour maladie pendant 2 mois peut donc perdre 5 jours ouvrables de congés payés. Mais l’absence du/de la salarié·e ne peut avoir pour effet d’entraîner une réduction de ses droits à congé plus que proportionnelle à la durée de cette absence.

Lorsque le nombre de jours ouvrables calculé n’est pas un nombre entier, la durée du congé est portée au nombre entier immédiatement supérieur.

#### Période d'acquisition des congés

Chez Fairness la période d'acquisition des congés est de du 1er Juin au 31 mai

#### Pour information: Règles de calcul général

Que le décompte se fasse en jours ouvrés ou jour ouvrable, un.e salarié.e a droit à 5 semaines de congés payés.

 En jour ouvré, le calcul se fera ainsi :  5 semaines x 5 jours ouvrés = 25 jours ouvrés. 
 

Un.e salarié.e acquiert donc 2.08 jours de congés par mois travaillés effectif.

Calcul : (5 semaines * 5 jours ouvrés) / 12 = 2.08

#### Règles de calcul avec l'accord d'entreprise

Avec l'accord d'entreprise, les salarié.e.s de Fairness vont obtenir **7 semaines de congés payés**

Le calcul se fera ainsi : 7 semaines * 5 jours ouvrés = 35 jours ouvrés

Un.e salarié acquiert donc 2.91 jours de congés par mois travaillés effectif.

Calcul : (7 semaines * 5 jours ouvrés) / 12 = 2.91

#### Autres jours de congés payés

Le/la salarié·e a droit, sur justification, à un congé spécifique rémunéré et assimilé à du temps de travail effectif pour la détermination de la durée du congé payé annuel.

La durée de ce congé spécifique est de :

- 4 jours pour son mariage ou pour la conclusion d’un pacte civil de solidarité ;
- 1 jour pour le mariage d’un enfant ;
- 3 jours pour chaque naissance survenue à son foyer ou pour l’arrivée d’un enfant placé en vue de son adoption. Ces jours d’absence ne se cumulent pas avec les congés accordés pour ce même enfant dans le cadre du congé de maternité ;
- 7 jours pour le décès d’un enfant. Si l’enfant est âgé de moins de 25 ans, le/la salarié·e a également droit a un congé supplémentaire, dit congé de deuil, d’une durée de 8 jours. Cette disposition s’applique également si la personne décédée âgée de moins de 25 ans est à la charge effective et permanente du/de la salarié·e ;
- 3 jours pour le décès de l’époux·se, concubin·e ou partenaire lié par un pacte civil de solidarité, du père, de la mère, du beau-père, de la belle-mère, d’un frère ou d’une sœur ;
- 2 jours pour l’annonce de la survenue d’un handicap chez un enfant.

### Découpage en issues

A.  Le compteur augmente en fonction du nimbre de jours de travail effectif effectué (issue : #383 )
B. Le compteur diminue dès que je prends un jour de congé payé (issue:  #384)

**Comment by benpaquier** [comment]
Merci @Volubyl pour cette superbe story, je sens déjà le casse tête arriver 🥰. Ça va être challengeant

Pour moi il y aura 2 points principaux pour arriver à afficher le nombre de jours de congé payé qu'il me reste pour cette année, qui au final correspond à la différence de:
- Calcul de jour total que l'on a accumulé, en utilisant les règles parfaitement décrites plus haut
- Calcul des jours que l'on a pris durant l'année. Là est la question: quelle est la source de vérité pour ce point là: Permacoop ? Fiche de paie ? J'aurais tendance à dire Permacoop, puisque les fiches de payes sont générées via les données présentes sur Permacoop

**Comment by florimondmanca** [comment]
On est d'accord qu'il faut donc fermer le ticket #364 qui fait doublon maintenant ?

**Comment by Volubyl** [comment]
@benpaquier 

> Calcul de jour total que l'on a accumulé, en utilisant les règles parfaitement décrites plus haut. Remarque: est ce qu'on base notre calcul à partir du 1er Juin 2023, puisque les compteurs on été remis à 0 à cette date là ? Je dirais oui

Les compteurs n'ont pas tout à fait été remis à 0 pour tout le monde. 

L'idée de la remise à 0 écrit dans l'accord d'entreprise visait à permettre aux personnes ayant eu un solde négatif de congé au 31 de bénéficier de jours de congés supplémentaires pour avoir un solde remis à 0 au 1er Juin.

Les personnes ayant eu un solde positif au 31 mai ont gardé leur solde positif ( elle n'ont pas perdu de jours)

> Calcul des jours que l'on a pris durant l'année. Là est la question: quelle est la source de vérité pour ce point là: Permacoop ? Fiche de paie ? J'aurais tendance à dire Permacoop, puisque les fiches de payes sont générées via les données présentes sur Permacoop

Ok pour moi

**Comment by Volubyl** [comment]
:wave:  pour info, j'ai scinder cette EPIC en deux #383 et #384

**Comment by florimondmanca** [comment]
> > Calcul des jours que l'on a pris durant l'année. Là est la question: quelle est la source de vérité pour ce point là: Permacoop ? Fiche de paie ? J'aurais tendance à dire Permacoop, puisque les fiches de payes sont générées via les données présentes sur Permacoop
> 
> Ok pour moi

Il y a une chose dont on peut être sûrs (ou en avoir confiance), c'est que le décompte de jours de congés sur les fiches de paie est correct.

Le plus probable est plutôt que Permacoop se trompe. Par exemple parce qu'on n'aura pas implémenté une des multiples règles ou exceptions, concernant les arrêts de travail par exemple. Toute cette complexité est déjà implémentée dans Cegid Loop (le progiciel de la compta) sur lequel des quantités de gens travaillent pour qu'il soit raccord avec la loi.

En ce sens, la source de vérité est selon moi les fiches de paie.

Permacoop ne serait qu'indicatif

D'ailleurs je crois comprendre que le besoin finalement c'est plutôt de savoir "en gros combien il m'en reste", "est-ce que je peux poser une semaine ici"

Le problème étant que les fiches de paie ne donne que le nb "acquis", et pas "ce qui sera encore dispo jusqu'à la fin de l'année"

Permacoop pourrait donc faire ce calcul simplifié.

En gros, sachant que la fiche de paie indique que tu en as acquis X entre le 1er juin dernier et aujourd'hui, et que tu en as déjà pris Y (aux yeux de Permacoop), alors jusqu'au 31 mai prochain il t'en reste encore Z.

Le calcul serait : 

```
Z = N - Y
```

où `N = X / (nb mois écoulés depuis le 1er juin) * 12` est le nb total de jours de congés sur l'année

L'avantage c'est que ça fait moins de paramétrage. Le nb de congés gagné chaque mois est inclus dans X.

Par contre, il faudrait "mettre à jour" X chaque mois. Ça pourrait être une nouvelle tâche de la gérance lors de la réception des fiches de paie (c'est pas long et suffit de le documenter dans le Wiki).

**Comment by Volubyl** [comment]
> Par contre, il faudrait "mettre à jour" X chaque mois. Ça pourrait être une nouvelle tâche de la gérance lors de la réception des fiches de paie (c'est pas long et suffit de le documenter dans le Wiki).

Par principe, je pense qu'une solution qui demande de la maintenance manuelle n'est pas une bonne solution car :

- risque d'oubli
- nécessite de garder en tête qu'il faut faire cette action (est-ce qu'un logiciel n'est il justement pas un moyen d'évacuer de la charge mentale ?)
- nécessite de prendre le temps de le faire (est-ce que ce temps ne pourrait pas être alloué à qqch d'autre  ? )

**Comment by florimondmanca** [comment]
Si on décide que ça vaut le coup en terme de maintenance de Permacoop (qu'on a déjà du mal à faire) de réimplémener la législation et les exceptions en matières de congés payés

Personnellement, j'en doute, c'est pour cela que je propose une solution "manuelle" (en réalité s'appuyant sur un process déjà bien rodé : l'établissement et la transmission des fiches de paie par la gérance https://gitlab.fairness.coop/fairness/documentation/-/wikis/Salaires-et-fiches-de-paie)

En tant que co-gérant ça me semble tout à fait gérable.

Même en cas d'oubli, en fait ce ne serait pas critique en général car le X ne sert qu'à obtenir le nb total de jours de congés. Là où ça deviendrait problématique ce serait lors de cas exceptionnels : les "congés acquis" progresseront alors moins vite dans la fiche de paie, et sans synchronisation Permacoop continuerait par exemple à croire qu'il y a 35 jours au total alors qu'en fait c'est peut-être devenu 32.6 en raison de N jours d'arrêt maladie.

**Comment by florimondmanca** [comment]
> est-ce que tu pourrais déplacer ton commentaire sur https://github.com/fairnesscoop/permacoop/issues/383 ?

Dans #383 j'ai du mal à comprendre quelle fonctionnalité serait ajoutée à Permacoop. Pour l'instant le ticket résume une méthode de calcul, qui a l'air correcte certes. Mais quel est le besoin ? Le nb de congés acquis est déjà indiqué dans la fiche de paie. Par contre, le nb de congés pouvant encore être posé, compte tenu des éventuels jours déjà posés dans le futur via Permacoop, ne l'est pas, et ça c'est l'objet du présent ticket.

En résumé, l'existence de #383 et le choix sur ce ticket 381 se résume selon moi au choix cardinal suivant : la question de la source de vérité

* Soit on réimplémente toutes les règles permettant d'être parfaitement synchro avec les fiches de paie ;
  * Perso je n'y suis pas favorable et je n'y mettrais pas mon énergie
  * Certes les jours de congés pris correspondent aux données de Permacoop, mais c'est bien Cegid Loop / la compta qui établit les jours de congés acquis en incorporant toute la législation française.
* Soit on imagine un mécanisme de synchronisation, qui pourrait être automatique (Cegid Loop a-t-il une API ?), ou de façon plus low-tech, en semi-manuel (mettre à jour une valeur qui permet le calcul).

**Comment by Volubyl** [comment]
@florimondmanca 

> Dans https://github.com/fairnesscoop/permacoop/issues/383 j'ai du mal à comprendre quelle fonctionnalité serait ajoutée à Permacoop. Pour l'instant le ticket résume une méthode de calcul, qui a l'air correcte certes. Mais quel est le besoin ?

Le besoin est d'avoir un compteur qui augmente en fonction du nombre de congé acquis.

Avant de rédigé cet issue, j'en ait parlé avec les  personnes présentes autour de moi (Hélène, Mathieu, Benoit principalement) et pour elles ce serait un besoin.

> Le nb de congés acquis est déjà indiqué dans la fiche de paie

Oui effectivement, ce nombre est déja indiqué mais même en ayant communiqué l'information, pour elles, l'envie d'avoir ce compteur demeure.

Ceci étant dit, j'ai rélu ton message et  je suis d'accord avec le fait que le risque d'erreur est assez important : plein de petites règles d'acquisition de congé auxquelles l'on ne pensera pas et donc il y aura certainement de la déscrynchro.

La solution proposée me semble la plus viable mais cependant j'ai des doutes quant à la viabilité sur le moyen/long terme.

Pour être honnête, je ne participerais pas à la mise à jour manuelle de Permacoop car à mes yeux (et pour mon cas personnel) le bénéfice que je vais en tirer est inférieur à la "charge mentale" que cela implique.

Est-ce que toi personellement tu souhaite effectuer cette MAJ chaque mois ?

**Comment by Volubyl** [comment]
je serai preneurs d'autres avis @ip512 @mmarchois  p-e ?

**Comment by mmarchois** [comment]
Je suis du même avis que @Volubyl sur le point "risque d'oubli". Quand on voit la galère que c'est de demander aux gens de remplir le faircalendar, je suis quasi sûr qu'il y aura des problèmes de reporting.
Je comprends aussi le point de @florimondmanca sur le risque de desynchro entre les fiches de paies (source de vérité) et permacoop.

Peut-être faudrait-il alors repenser le besoin. Initialement, c'était de savoir combien de jours je pouvais poser. 

Dans un premier temps, on pourrait tout simplement remonter le nombre de jours pris sur une année par salarié (que ce soit bien plus clair que le listing d'aujourd'hui), ce qui donnera un indicateur par rapport au nombre de jours de congés restants :
- Si, sur l'année, j'ai posé 5 jours, je sais que je suis assez large
- Si, sur l'année, je suis déjà à 20 jours, je vais m'orienter vers ma fiche de paie pour savoir mon compteur restant.

Je vois plus cette feature comme un indicateur/curseur pour savoir où tu en es. Ce ne sera pas couteux en termes de développement : nous avons déjà toutes les données.

@florimondmanca @Volubyl qu'en pensez-vous ?

**Comment by florimondmanca** [comment]
@Volubyl 

> Est-ce que toi personellement tu souhaite effectuer cette MAJ chaque mois ?

Si c'est quelque chose qu'on considère important pour l'équipe, je pense qu'on pourrait décider de l'intégrer au mandat de cogérance (comme pour l'établissement des fiches de paie etc). Et donc la question ne sera pas si moi ou un autre membre de la cogérance "souhaiterait" faire la MAJ, elle devra être faite, et donc elle le sera (sauf manquement de la cogérance, comme si on "oubliait" d'établir les fiches de paie en fin de mois : ça n'arrive pas car on y pense et c'est dans les process habituels).

Ça évite les problèmes d'oublis car contrairement à ce que semble penser @mmarchois , l'idée n'était pas de mettre la charge sur tout le monde (contrairement à FairCalendar qui est forcément complètement décentralisé), mais de la centraliser sur quelques personnes (la cogérance) qui en auront la responsabilité, documentée via les process

> remonter le nombre de jours pris sur une année par salarié

C'est vrai qu'on n'a pas cette info dans FairCalendar pour l'instant

Ça correspond au Y dans mon calcul ci-dessus

Sachant nous-mêmes combien de jours il nous reste globalement, on pourrait en effet s'en sortir pour savoir si on est encore "large"

Ça voudrait donc dire que ce ticket 381 n'aurait pas lieu d'être (on considèrerait qu'on n'a finalement pas tant besoin de voir le nb de congés restants dans Permacoop), et qu'il ne faudrait garder que #383
